[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
via_ir = true
ffi = true

remappings = [
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
    'forge-multibaas/=lib/forge-multibaas/src/'
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
